name: Pull request integration tests on VM

on:
  workflow_call:
    inputs:
      kernel:
        description: 'Path to the kernel image to use for the tests'
        required: true
        type: string

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Clean up disk space
        run: |
          docker system prune -af
          docker volume prune -f
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils qemu-system-x86
      - name: Run VM integration tests
        run: |
          KERNEL=${{ inputs.kernel }} sudo make -C test/vm && [ -f testoutput/success ]
          sudo make -C test/vm change-owner
        timeout-minutes: 60
      - name: Upload integration test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Logs
          path: |
            testoutput/*.log
            testoutput/kind
      - name: Report coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./testoutput/itest-covdata.txt
          flags: integration-test
